#############################################################################
# Makefile for building: mutingAnt
# Generated by qmake (2.01a) (Qt 4.7.4) on: dim. avr. 1 16:13:14 2012
# Project:  projet.pro
# Template: app
# Command: /usr/bin/qmake -o Makefile projet.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_WEBKIT -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -m64 -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -m64 -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++-64 -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtNetwork -I/usr/include/qt4/QtGui -I/usr/include/qt4 -I. -I.
LINK          = g++
LFLAGS        = -m64 -Wl,-O1
LIBS          = $(SUBLIBS)  -L/usr/lib/x86_64-linux-gnu -lQtGui -lQtNetwork -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = station.cpp \
		manageStation.cpp \
		mainframe.cpp \
		HelloModule.cpp \
		main.cpp moc_mainframe.cpp \
		moc_HelloModule.cpp \
		moc_manageStation.cpp
OBJECTS       = station.o \
		manageStation.o \
		mainframe.o \
		HelloModule.o \
		main.o \
		moc_mainframe.o \
		moc_HelloModule.o \
		moc_manageStation.o
DIST          = /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		projet.pro
QMAKE_TARGET  = mutingAnt
DESTDIR       = 
TARGET        = mutingAnt

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_interface.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: projet.pro  /usr/share/qt4/mkspecs/linux-g++-64/qmake.conf /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/x86_64-linux-gnu/libQtGui.prl \
		/usr/lib/x86_64-linux-gnu/libQtNetwork.prl \
		/usr/lib/x86_64-linux-gnu/libQtCore.prl
	$(QMAKE) -o Makefile projet.pro
/usr/share/qt4/mkspecs/common/g++.conf:
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/x86_64-linux-gnu/libQtGui.prl:
/usr/lib/x86_64-linux-gnu/libQtNetwork.prl:
/usr/lib/x86_64-linux-gnu/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -o Makefile projet.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/mutingAnt1.0.0 || $(MKDIR) .tmp/mutingAnt1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/mutingAnt1.0.0/ && $(COPY_FILE) --parents mainframe.h HelloModule.h station.h manageStation.h .tmp/mutingAnt1.0.0/ && $(COPY_FILE) --parents station.cpp manageStation.cpp mainframe.cpp HelloModule.cpp main.cpp .tmp/mutingAnt1.0.0/ && $(COPY_FILE) --parents interface.ui .tmp/mutingAnt1.0.0/ && (cd `dirname .tmp/mutingAnt1.0.0` && $(TAR) mutingAnt1.0.0.tar mutingAnt1.0.0 && $(COMPRESS) mutingAnt1.0.0.tar) && $(MOVE) `dirname .tmp/mutingAnt1.0.0`/mutingAnt1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/mutingAnt1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_mainframe.cpp moc_HelloModule.cpp moc_manageStation.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainframe.cpp moc_HelloModule.cpp moc_manageStation.cpp
moc_mainframe.cpp: ui_interface.h \
		HelloModule.h \
		manageStation.h \
		station.h \
		mainframe.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) mainframe.h -o moc_mainframe.cpp

moc_HelloModule.cpp: HelloModule.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) HelloModule.h -o moc_HelloModule.cpp

moc_manageStation.cpp: station.h \
		manageStation.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) manageStation.h -o moc_manageStation.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_interface.h
compiler_uic_clean:
	-$(DEL_FILE) ui_interface.h
ui_interface.h: interface.ui
	/usr/bin/uic-qt4 interface.ui -o ui_interface.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

####### Compile

station.o: station.cpp station.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o station.o station.cpp

manageStation.o: manageStation.cpp manageStation.h \
		station.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o manageStation.o manageStation.cpp

mainframe.o: mainframe.cpp mainframe.h \
		ui_interface.h \
		HelloModule.h \
		manageStation.h \
		station.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainframe.o mainframe.cpp

HelloModule.o: HelloModule.cpp HelloModule.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o HelloModule.o HelloModule.cpp

main.o: main.cpp mainframe.h \
		ui_interface.h \
		HelloModule.h \
		manageStation.h \
		station.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

moc_mainframe.o: moc_mainframe.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainframe.o moc_mainframe.cpp

moc_HelloModule.o: moc_HelloModule.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_HelloModule.o moc_HelloModule.cpp

moc_manageStation.o: moc_manageStation.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_manageStation.o moc_manageStation.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

